BMD-7309: send notifications to SNS instead of SQS
BerlingskeMedia/aria_datadispatcher pull request #30
Opened 2021-04-26 09:56 UTC by bmxpapa

2021-04-27 07:12 UTC, bmxmaza approved these changes

2021-04-27 08:18 UTC, bmxpiku requested changes

2021-04-27 08:35 UTC, bmxpapa commented on server/kafka.js
> +  module.exports.healthcheck = () => true;
previously in that case application was throw with a function doesnt exists, not sure if false or void is a better option (then we need to change the place where healthcheck is checked)

2021-04-27 08:36 UTC, bmxpapa commented on server/sns.js
> +const sns = new AWS.SNS({ apiVersion: '2010-03-31', endpoint: SNS_ENDPOINT } );
it is an API version

2021-04-27 08:39 UTC, bmxpapa commented on server/sns.js
> +AWS.config.update({ accessKeyId: AWS_ACCESS_KEY_ID, secretAccessKey: AWS_SECRET_ACCESS_KEY, region: AWS_REGION });
https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/loading-node-credentials-environment.html

2021-04-27 08:46 UTC, bmxpapa commented on server/notifications_events.js
> +          console.info('event_id:', JSON.stringify(event_id));
It was for debug purpose for me: more descriptive,  I will remove it

2021-04-27 08:52 UTC, bmxpapa commented on server/kafka.js
> +  module.exports.healthcheck = () => true;
nvm, fixed to false

2021-04-27 09:34 UTC, bmxpiku commented on server/sns.js
> +const sns = new AWS.SNS({ apiVersion: '2010-03-31', endpoint: SNS_ENDPOINT } );
I mean :D I get that, although maybe this should go via some env var? so its easier to upgrade?

2021-04-27 09:39 UTC, bmxpiku approved these changes

2021-08-25 06:30 UTC, bmxmaza approved these changes

2021-09-20 08:16 UTC, merged