CM-352 added set event_id for missing event types
BerlingskeMedia/aria_datadispatcher pull request #45
Opened 2022-07-15 11:33 UTC by bmxpadu

### Jira ticket:
https://berlingskemedia.atlassian.net/browse/CM-352

### Pre/Post release actions:
(none)

2022-07-15 11:57 UTC, bmxsele requested changes

2022-07-15 11:57 UTC, bmxsele commented on server/notifications_events.js
> +    return `${requestActionType}_${requestID.replace(/^(req_id_\\s_)|^(req_id_)/, '')}`;
Can't we just do: 

```suggestion
    return requestID.replace('req_id', requestActionType);
```

?

2022-07-15 12:00 UTC, bmxsele commented on server/notifications_events.js
> +    return `${requestActionType}_${requestID.replace(/^(req_id_\\s_)|^(req_id_)/, '')}`;
Or:

```suggestion
    return `${requestActionType}_${requestID.replace('req_id_', ''}.trim()`;
```

2022-07-15 12:01 UTC, bmxsele commented on server/notifications_events.js
> +    return `${requestActionType}_${requestID.replace(/^(req_id_\\s_)|^(req_id_)/, '')}`;
OK, we can't - discussed on slack

2022-07-15 12:02 UTC, dgolabek-sii commented on server/notifications_events.js
> +    return `${requestActionType}_${requestID.replace(/^(req_id_\\s_)|^(req_id_)/, '')}`;
`return requestID.replace(/^req_id_(\\s_)?/, requestActionType);`

2022-07-15 12:05 UTC, dgolabek-sii commented on server/notifications_events.js
> +  }
as I understand we get events in the format corresponding to this code and not like in the ticket description - `AMPSEventGUID` ?

2022-07-25 12:08 UTC, bmxpadu commented on server/notifications_events.js
> +  }
added it

2022-07-25 12:26 UTC, dgolabek-sii approved these changes

2022-07-27 08:04 UTC, bmxsele approved these changes

2022-08-16 09:12 UTC, bmxsele approved these changes

2022-08-16 09:14 UTC, merged